new pages for complaint feedback and room booking
IMGIITRoorkee/omniport-frontend-bhawan-app pull request #41
Opened 2024-03-29 13:45 UTC by Hardik-2311

2024-03-30 14:13 UTC, Hardik-2311 commented
@beingnoble03 kindly review

2024-03-30 14:13 UTC, Hardik-2311 commented
https://github.com/IMGIITRoorkee/omniport-frontend-bhawan-app/assets/126074137/f6b4d96a-2118-40a6-917e-f57f6608e27a

2024-04-05 17:34 UTC, beingnoble03 requested changes

2024-04-05 17:34 UTC, beingnoble03 commented on src/components/feebback-card-new/index.js
> +                            <td className={tailwindWrapper("border px-4 py-2")}>2024-03-29</td>
dummy data?

2024-04-05 17:34 UTC, beingnoble03 commented on src/components/events-new/index.js
> +      console.log(this.props.activeHostel)
remove this statement

2024-04-05 17:34 UTC, beingnoble03 commented on src/components/complaints-new/index.js
> +                        <span>{"   |   "}</span>
why is this `"   |   "`? i think we should use padding or margin instead.

2024-04-05 17:34 UTC, beingnoble03 commented on src/components/book-room-new/index.js
> +                    {/* Submit Button */}
remove this comment

2024-04-05 17:34 UTC, beingnoble03 commented on src/components/book-room-new/index.js
> +                    {/* Date Inputs */}
remove this

2024-04-05 17:34 UTC, beingnoble03 commented on src/components/book-room-new/index.js
> +                {/* Form */}
remove

2024-04-05 17:34 UTC, beingnoble03 commented on src/components/book-room-new/index.js
> +            console.log(index)
remove

2024-04-05 17:34 UTC, beingnoble03 commented on src/components/book-room-new/index.js
> +        console.log(this.state.fromDate, this.state.endDate, this.state.visitors);
remove

2024-04-06 05:06 UTC, Hardik-2311 commented
@beingnoble03  done changes

2024-04-06 12:59 UTC, beingnoble03 requested changes

2024-04-06 12:59 UTC, beingnoble03 commented on src/components/Feedback/index.js
> +        console.log(this.state);
remove

2024-04-06 12:59 UTC, beingnoble03 commented on src/components/book-room-new/index.js
> +
extra line? lint with prettier once

2024-04-06 12:59 UTC, beingnoble03 commented on src/components/book-room-new/index.js
> +
extra line?

2024-04-06 12:59 UTC, beingnoble03 commented on src/components/book-room-new/index.js
> +                                            Identiti Proof
typo

2024-04-06 12:59 UTC, beingnoble03 commented on src/components/feebback-card-new/index.js
> +                        {/* real data will be done after feedback actions */}
```suggestion
                        {/* TODO: real data will be done after feedback actions */}
```

2024-04-07 09:03 UTC, beingnoble03 approved these changes

2024-04-07 09:04 UTC, merged